### PR TITLE
[WIP] switch from autotools -> cmake

### PR DESCRIPTION
**Pull request by js947**
- [x] Switch build from autotools -> cmake
- [x] Use ctest for running tests
- [ ] Use `BuildTests` to select whether tests should be build
- [x] Update `README.md`

### CODE REVIEW

**Comment by js947** [comment]
Build failures with `gcc` seem to be due to a compiler bug. Can be fixed by `-fpermissive`.

**Comment by js947** [comment]
I'm not sure that having the tests split into different excutables for `ctest` is better or worse. On the plus side the output from ctest looks nicer:

```
Test project /home/js947/lbmdem_cmake-build
    Start 1: lb_node_2d
1/2 Test #1: lb_node_2d .......................   Passed    0.00 sec
    Start 2: lb_node_3d
2/2 Test #2: lb_node_3d .......................   Passed    0.00 sec
```

but this might mean missing out on some of the features of the catch.hpp framework?

**Comment by cbgeo** [comment]
Each test file has multiple tests and like you say it means I have to run multiple executables to test features like only `[node]` or `[2D]` condition. Maybe keep them as one executable?

**Comment by cbgeo** [comment]
We need `-coverage` flag for coverage analysis.

**Pull request merged**
